# Generated by Django 2.2.6 on 2020-01-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('codigo_dane', models.CharField(max_length=15, verbose_name='Codigo DANE')),
                ('departamento', models.CharField(max_length=18, verbose_name='Departamento')),
                ('municipio', models.CharField(max_length=27, verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'municipio',
                'managed': False,
            },
        ),
    ]
