# Generated by Django 2.2.6 on 2020-01-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrigenContacto',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('contacto', models.CharField(max_length=30, verbose_name='Contacto')),
            ],
            options={
                'verbose_name': 'Origen de Contacto',
                'verbose_name_plural': 'Origen de Contactos',
                'db_table': 'origen_contacto',
                'managed': False,
            },
        ),
    ]
