# Generated by Django 2.2.6 on 2020-01-30 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiljuridico', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfiljuridico',
            options={'managed': False, 'ordering': ['codigo'], 'verbose_name': 'Perfil Jurídico', 'verbose_name_plural': 'Perfil Jurídicos'},
        ),
    ]
