# Generated by Django 2.2.6 on 2020-01-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseDocumento',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('documento', models.CharField(blank=True, max_length=150, null=True, verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Clase de Documento',
                'verbose_name_plural': 'Clases de Documentos',
                'db_table': 'clase_documento',
                'managed': False,
            },
        ),
    ]
