# Generated by Django 2.2.6 on 2020-01-24 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSeguimiento',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('seguimiento', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo_seguimiento',
                'managed': False,
            },
        ),
    ]
