# Generated by Django 2.2.6 on 2020-01-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfilasesor',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('perfil', models.CharField(max_length=50, verbose_name='Perfil Asesor')),
            ],
            options={
                'verbose_name': 'Perfil del Asesores',
                'verbose_name_plural': 'Perfiles de Asesores',
                'db_table': 'perfilasesor',
                'managed': False,
            },
        ),
    ]
