# Generated by Django 2.2.6 on 2020-01-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subitemseguimiento',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('subsegumiento', models.CharField(db_column='subSegumiento', max_length=30)),
                ('seguimiento', models.IntegerField()),
            ],
            options={
                'db_table': 'subitemseguimiento',
                'managed': False,
            },
        ),
    ]
