# Generated by Django 2.2.6 on 2020-01-30 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abogados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbabogados',
            name='actualizacion',
            field=models.ForeignKey(blank=True, db_column='actualizacion', null=True, on_delete=django.db.models.deletion.PROTECT, to='asesores.AsesoresDb', verbose_name='Nombre del asesor'),
        ),
    ]
