# Generated by Django 2.2.6 on 2020-01-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesoresdb',
            name='direccion2',
            field=models.CharField(blank=True, max_length=154, null=True, verbose_name='Dirección 2'),
        ),
    ]
