# Generated by Django 2.2.6 on 2020-01-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desicion',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('desicion', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'desicion',
                'managed': False,
            },
        ),
    ]
