# Generated by Django 2.2.6 on 2020-01-23 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genero', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genero',
            options={'managed': False, 'verbose_name': 'Genero', 'verbose_name_plural': 'Generos'},
        ),
    ]
